// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export const microProps: { nbsName: string } = {
  nbsName: window.__MICRO_APP_NAME__,
  ...window?.microApp?.getData(),
};
