// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!

import React from "react";
import ReactDOM from "react-dom/client";
import { createBrowserRouter, RouterProvider } from "react-router-dom";
import "./index.css";
import "./lang";

const routeFiles = (import.meta as any).glob("../../src/pages/**/index.tsx", {
  eager: true,
});
console.log("routeFiles", routeFiles);

if (
  Object.keys(routeFiles).length == 1 &&
  routeFiles["../../src/pages/index.tsx"]
) {
  const Page = (routeFiles["../../src/pages/index.tsx"] as any).default;
  ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
    <React.StrictMode>
      <Page />
    </React.StrictMode>
  );
} else {
  const router = createBrowserRouter(
    Object.keys(routeFiles)
      .filter(
        (key) => !key.includes("components") && !key.includes("components")
      )
      .map((key) => {
        const paths = key.split("/");
        const path = paths.slice(2, -1).reduce((acc, path) => {
          return acc + `/${path}`;
        }, "");
        const Page = (routeFiles[key] as any).default;
        return {
          path: path === "home" || path === "index.tsx" ? "/" : `${path}`,
          element: <Page />,
        };
      })
  );
  ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
    <React.StrictMode>
      <RouterProvider router={router} />
    </React.StrictMode>
  );
}
