// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!

import React from "react";
import ReactDOM from "react-dom/client";
import { createBrowserRouter, RouterProvider } from "react-router-dom";
import { ConfigProvider } from "antd";
import zhCN from "antd/locale/zh_CN";
import "./index.css";
import "./lang";
import { microProps } from "./index";

const routeFiles = (import.meta as any).glob("../../src/pages/**/index.tsx", {
  eager: true,
});
console.log("routeFiles", routeFiles);
console.log("microProps", microProps);

const router = createBrowserRouter(
  Object.keys(routeFiles)
    .filter((key) => !key.includes("components") && !key.includes("components"))
    .map((key) => {
      const paths = key.split("/");
      const path = paths.slice(2, -1).reduce((acc, path) => {
        return acc + `/${path}`;
      }, "");
      const Page = (routeFiles[key] as any).default;
      return {
        path: path === "home" || path === "index.tsx" ? "/" : `${path}`,
        element: <Page />,
      };
    }),
  { basename: microProps.baseroute }
);
ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <ConfigProvider locale={zhCN}>
      <RouterProvider router={router} />
    </ConfigProvider>
  </React.StrictMode>
);
